# Generated by Django 5.1.5 on 2025-01-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_item_options_alter_order_options_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В ожидании', 'В ожидании'), ('Оплачено', 'Оплачено'), ('Готово', 'Готово')], default='В ожидании', max_length=10, verbose_name='Статус'),
        ),
    ]
